### ISSUE TITLE
Python 3 compatibility?

### ISSUE THREAD

**Issue by thedodd** [jkinred/psphere#9]
What is the status on Python 3 support?

**Comment by caesarshift** [comment]
I've added a fork here: https://github.com/caesarshift/psphere

I've switched dependency to suds-jurko and run the code through 2to3.py

The main page example of printing the current time is working, but I have not yet tested anything else.

Feedback welcome.

**Comment by michaelrice** [comment]
@caesarshift Im curious if its even worth the effort when vmware provides [pyvmomi](https://github.com/vmware/pyvmomi/)?

**Comment by intr1nsic** [comment]
I would 2nd the move to pyvmomi.  I think it's probably best to mark psphere as "no longer maintained" and point users to pyvmomi.

**Comment by jkinred** [comment]
I've just updated the README with a sunset clause. pyvmomi is the place to start for new users.

It's been a couple of years since I looked at pyvmomi, though when I looked it wasn't very Pythonic and there was an opening to provide a Pythonic API _on top_ of pyvmomi. That would be pretty cool and someone may well have done so.

If anyone comes across something, please let me know for curiosities sake.

Thanks everyone!

**Comment by jkinred** [comment]
@caesarshift - If you feel that it's worth building on top of what is here... let me know and I can drive the traffic toward your fork and transfer any PyPI access and such.

I'd like to keep this repo as it's good publicity when job hunting :1st_place_medal:.
